# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a542df799911535f328cf1fb858e8c4ec72b37bb26ab2d1ca892d6f68626cc5868d04c311f42883256e3c4331598e215e4b9fff0635c67b8af1a6fed9c52fe

test:
  secret_key_base: 4eb04b5120de5966e8c25fa30e0437c491830a80d7cfa08ac8c5bc43723c563df6fbb91419aec1659ac2d684e061d104326943871fc8c4329a7655afe8fa82b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
